theme: minima
title: My First Page on GitHub
author: I. C.
description: This is my first project hosted on GitHub. It demonstrates my journey in web development and programing skills!
google_fonts:
  - family: 'Open Sans'
