theme: minima
title: My First Page on GitHub
author: I. C.
description: This is my first project hosted on GitHub. It demonstrates my journey in web development, showcasing fundamental concepts like HTML, CSS, and JavaScript. Stay tuned for more updates!
